WebPurple/site

package.json, webpack.config.js
=> [https://github.com/kitos/web-purple/issues/43] Added fetch polyfill

src/components/app.header.jsx
Header alignment issue fixed in ie-11, verified in ie-11; chrome and fx (latest versions)
npm run test and npm run lint passes.
=> Fixed issue with the header alignment in IE11

src/server/controllers/auth/fb.strategy.conf.js, src/server/controllers/posts.controller.js
=> :bug: fix #57 - now longLiveAccessToken is used for getting page access token

package.json, test/containers/feed/feed.actions.test.js, test/containers/feed/feed.reducer.test.js, test/containers/feed/new-post/new-post.actions.test.js, test/containers/feed/new-post/new-post.reducer.test.js, test/containers/feed/post-edit.reducer.test.js, test/containers/navigation/navigation-bar.reducer.test.js, test/reducers/user.reducer.test.js, test/server/controllers/auth.controller.test.js, test/server/controllers/auth/fb.strategy.conf.test.js, test/server/controllers/auth/vk.strategy.conf.test.js, test/server/controllers/page-info.controller.test.js, test/server/controllers/posts.controller.test.js, test/server/controllers/rss.controller.test.js, test/server/controllers/user.controller.test.js, test/server/services/facebook.service.test.js, test/server/utils/security-utils.test.js, test/utils/ajax.test.js, test/utils/common-utils.test.js
- resolve new dependencies
- change existed tests
- added _enzyme_ & _identity-obj-proxy_ for future tests
=> Replace mocha with jest

src/components/footer.jsx, src/components/icons/webpurple-logo-icon.jsx, src/containers/app/app.jsx
*About set of color in the logo: I just replace the white with 0.24 opacity to current value, I hope it's possible.
=> implement adaptive layout of footer component

src/components/diamond.jsx, src/components/event-diamond.jsx, src/components/home-page/past-events.jsx, src/containers/app/app.jsx
* Diamond: adding shadow diamond, refactoring
* moving Diamond content to the EventDiamond
* app: adding colors for shadows
=> Diamond refactoring

src/components/event-page/event-page.jsx, src/components/login/login-popup.jsx, src/containers/events/event-page.jsx, src/containers/header/header.jsx, src/reducers/current-event.reducer.js, src/reducers/user.reducer.js, src/server/services/events.service.js
I fix several bugs related to auth process
Also I fix Current-Event reducer, remove unnecessery actions
=> Social auth

src/components/home-page/past-events.jsx
* move some diamonds for iPad
* formatting
=> Past events: markup for iPad

src/components/page-filter/index.jsx
=> Fixed search placeholder on speakers page

src/components/footer.jsx
* Added contributors link
* Changed some styles
=> #185 Add link to /contributors page to footer

src/components/datepicker/datepicker.css, src/components/datepicker/datepicker.jsx, src/components/datepicker/datepicker.less, src/containers/events/edit-event-form.jsx
https://github.com/kitos/web-purple/issues/173
* move react datepicker to the common component, 
* stylizing datepicker
=> #173 Stylize datepicker

src/components/event-page/talks/talk.jsx
=> 🐛 added condition to remove an extra comma

.flowconfig, .gitignore, package.json, readme.md
* added Flow, flow-typed and babel dependencies
* updated Readme
=> Flow integration

src/components/home-page/upcoming-events-block.jsx
Related to issue #181 
Lines 39 and 149 are just strange changes made by Atom.
=> 🐛 Fixed component's footer margin

src/components/footer.jsx
=> Fix email address typo

src/components/event-page/talks/talks.jsx
=> 🐛 added a fix for padding in the speakers block

src/components/event-page/event-page.jsx, src/components/events-page/event-list.jsx
=> Fix empty data in location and time

src/pages/event/meetup-24.yaml
=> Remove empty string tag from meetup-24

src/components/event-page/talks/talk.jsx
=> Remove unnecessary commas from Speaker

src/components/speaker-card/speaker-card.jsx, src/components/speaker-talks/speaker-talks.jsx, src/utils/hover-link.js
fix for issue #254 
Still I believe we should work on responsive design in tablets too.
=> fix: talks dialog overlapped photo on mobile

package.json, src/components/common/popup.jsx, src/components/common/video.jsx, src/components/event-page/talks/talk.jsx, src/pages/event/meetup-1.yaml, src/pages/event/meetup-20.yaml, src/pages/event/meetup-22.yaml, src/pages/event/meetup-24.yaml, src/pages/event/meetup-25.yaml, src/pages/event/meetup-26.yaml, src/pages/event/meetup-27.yaml, src/templates/event.template.js, yarn.lock
=> feature: add video to events

src/components/common/loader.js, src/components/common/video.jsx
Preloader should have transparent background
=> feat(loader): use svg instead of div

src/components/layout.jsx
Main container is now take all available height
=> 🔧 footer is not stick to the bottom

.all-contributorsrc, package-lock.json, package.json, readme.md
- initialized config
- added  links according to https://github.com/WebPurple/site/graphs/contributors + badge
- prettify README.md
link to #311
=> #311 Add all-contributors

package-lock.json, package.json
=> fix(package): update recompose to version 0.30.0

src/components/popup.jsx, src/components/speaker-talks/speaker-talks.jsx
=> fix: 🐛#316 set arrow style according to the placement

src/components/event-page/event-page.jsx
=> fix: 🐛 #358 - change import to make WebPurple great again

src/components/blog/article-card.jsx, src/pages/blog.js, src/templates/blog-post.template.js, src/utils/language-utils.js
=> feat - ⌚ add reading time to the article

package.json, src/components/event-diamond.jsx
#402 
title showing has been fixed. after fix:
=> fix: talk title crop

src/pages/event/meetup-36.yaml, src/pages/event/meetup-37.yaml, src/pages/event/meetup-38.yaml
=> fix(event-tags): make tags consistent
